# Generated by Django 4.2.7 on 2023-11-18 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_task_options_remove_task_task_task_tags_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["status", "-datetime"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="done",
            new_name="status",
        ),
    ]
