# Generated by Django 4.2.7 on 2023-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_task_options_rename_done_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
